rails/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
end

rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/app/models/user.rb
class User < ApplicationRecord
end

rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update!(user_params)
    redirect_to user
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Myapp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

rails/app/views/users/_form.html.haml
= form_with model: @user, url: @user.new_record? ? users_path : user_path(@user)  do |f|
  = f.label :name
  = f.text_field :name
  = f.submit @user.new_record? ? "Create" : "Submit"

rails/app/views/users/edit.html.haml
%h1= "Edit #{@user.name}"

= render 'form'

:javascript
  document.querySelector('[name="user[name]"]').addEventListener('input', (e) => {
    document.querySelector('h1').innerText = `Edit ${e.target.value}`
  })

rails/app/views/users/index.html.haml
%h1 Users
%table
  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= l(user.created_at)
        %td= link_to "View", user_path(user)

= link_to "Create", new_user_path

rails/app/views/users/new.html.haml
%h1 New user

= render 'form'

rails/app/views/users/show.html.haml
%h1= "User #{@user.name}"

%p= "Created: #{l(@user.created_at)}"
%p= "Last update: #{l(@user.updated_at)}"

= link_to 'Edit', edit_user_path(@user)